obj-$(CONFIG_MACH_MSM8916_C50_MPCS_US) += board-8916-c50.o
obj-$(CONFIG_MACH_MSM8916_C50_TMO_US) += board-8916-c50.o
obj-$(CONFIG_MACH_MSM8916_G4STYLUSN_MPCS_US) += board-8916-g4stylusn.o
obj-$(CONFIG_MACH_MSM8916_G4STYLUSN_TMO_US) += board-8916-g4stylusn.o


obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_LGE_PM_CHARGER_TEMP_SCENARIO_COMMON) += lge_charging_scenario.o

obj-$(CONFIG_LGE_PM) += lge_gpio_debug.o
obj-$(CONFIG_LGE_PM) += lge_monitor_thermal.o

obj-$(CONFIG_MACH_LGE) += lge_lcd_misc_ctrl.o
