#
# Makefile for the TD4191 drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += lge_touch_core.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += touch_synaptics.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += touch_synaptics_ds5_fw_upgrade.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += touch_synaptics_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_LGE_SYNAPTICS_TD4191) += DS5/
